# Generated by Django 4.1.2 on 2022-12-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
