# Generated by Django 4.1.2 on 2022-12-18 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_alumni_batch_alter_alumni_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='batch',
            new_name='batch_id',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='program',
            new_name='program_id',
        ),
    ]
