# Generated by Django 4.1.2 on 2022-12-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_batch_alumni_batch_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='batch_id',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='program_id',
            new_name='program',
        ),
    ]
