# Generated by Django 4.1.2 on 2022-12-04 15:12

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_alumni_avator_alter_alumni_batch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkAlumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('file_url', models.FileField(blank=True, null=True, upload_to=accounts.models.upload_to)),
            ],
        ),
    ]
