# Generated by Django 4.1.2 on 2022-12-05 12:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bulkalumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkalumni',
            name='file_url',
            field=models.FileField(upload_to=accounts.models.upload_to),
        ),
    ]
