# Generated by Django 4.1.2 on 2022-12-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_bulkalumni_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkalumni',
            name='description',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
    ]
