# Generated by Django 4.1.2 on 2022-12-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_bulkalumni_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.FileField(upload_to='reports/'),
        ),
    ]
