# Generated by Django 4.1.2 on 2022-12-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alumni_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='hash',
            new_name='hash_data',
        ),
    ]
