# Generated by Django 4.1.2 on 2022-12-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_report_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
