# Generated by Django 4.1.2 on 2022-12-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_report_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='entries',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
