export const DASHBOARD_REQUEST = 'DASHBOARD_REQUEST'
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS'
export const DASHBOARD_FAIL = 'DASHBOARD_FAIL'


export const DASHBOARD_TABLE_REQUEST = 'DASHBOARD_TABLE_REQUEST'
export const DASHBOARD_TABLE_SUCCESS = 'DASHBOARD_TABLE_SUCCESS'
export const DASHBOARD_TABLE_FAIL = 'DASHBOARD_TABLE_FAIL'