export const ALUMNI_REQUEST = 'ALUMNI_REQUEST'
export const ALUMNI_SUCCESS = 'ALUMNI_SUCCESS'
export const ALUMNI_FAIL = 'ALUMNI_FAIL'

export const BULK_ALUMNI_REQUEST = 'BULK_ALUMNI_REQUEST'
export const BULK_ALUMNI_SUCCESS = 'BULK_ALUMNI_SUCCESS'
export const BULK_ALUMNI_FAIL = 'BULK_ALUMNI_FAIL'