export const ALUMNI_REQUEST = 'ALUMNI_REQUEST'
export const ALUMNI_SUCCESS = 'ALUMNI_SUCCESS'
export const ALUMNI_FAIL = 'ALUMNI_FAIL'

export const BULK_ALUMNI_REQUEST = 'BULK_ALUMNI_REQUEST'
export const BULK_ALUMNI_SUCCESS = 'BULK_ALUMNI_SUCCESS'
export const BULK_ALUMNI_FAIL = 'BULK_ALUMNI_FAIL'

export const LIST_ALL_ALUMNI_REQUEST = 'LIST_ALL_ALUMNI_REQUEST'
export const LIST_ALL_ALUMNI_SUCCESS = 'LIST_ALL_ALUMNI_SUCCESS'
export const LIST_ALL_ALUMNI_FAIL = 'LIST_ALL_ALUMNI_FAIL'

export const LIST_BS_ALUMNI_REQUEST = 'LIST_BS_ALUMNI_REQUEST'
export const LIST_BS_ALUMNI_SUCCESS = 'LIST_BS_ALUMNI_SUCCESS'
export const LIST_BS_ALUMNI_FAIL = 'LIST_BS_ALUMNI_FAIL'


export const LIST_MS_ALUMNI_REQUEST = 'LIST_MS_ALUMNI_REQUEST'
export const LIST_MS_ALUMNI_SUCCESS = 'LIST_MS_ALUMNI_SUCCESS'
export const LIST_MS_ALUMNI_FAIL = 'LIST_MS_ALUMNI_FAIL'

export const LIST_PHD_ALUMNI_REQUEST = 'LIST_PHD_ALUMNI_REQUEST'
export const LIST_PHD_ALUMNI_SUCCESS = 'LIST_PHD_ALUMNI_SUCCESS'
export const LIST_PHD_ALUMNI_FAIL = 'LIST_PHD_ALUMNI_FAIL'

export const LIST_BATCH_REQUEST = 'LIST_BATCH_REQUEST'
export const LIST_BATCH_SUCCESS = 'LIST_BATCH_SUCCESS'
export const LIST_BATCH_FAIL = 'LIST_BATCH_FAIL'

export const LIST_PROGRAM_REQUEST = 'LIST_PROGRAM_REQUEST'
export const LIST_PROGRAM_SUCCESS = 'LIST_PROGRAM_SUCCESS'
export const LIST_PROGRAM_FAIL = 'LIST_PROGRAM_FAIL'


export const ALUMNI_UPDATE_REQUEST = 'ALUMNI_UPDATE_REQUEST'
export const ALUMNI_UPDATE_SUCCESS = 'ALUMNI_UPDATE_SUCCESS'
export const ALUMNI_UPDATE_FAIL = 'ALUMNI_UPDATE_FAIL'

export const ALUMNI_DATA_REQUEST = 'ALUMNI_DATA_REQUEST'
export const ALUMNI_DATA_SUCCESS = 'ALUMNI_DATA_SUCCESS'
export const ALUMNI_DATA_FAIL = 'ALUMNI_DATA_FAIL'



export const ALUMNI_SEARCH_REQUEST = 'ALUMNI_SEARCH_REQUEST'
export const ALUMNI_SEARCH_SUCCESS = 'ALUMNI_SEARCH_SUCCESS'
export const ALUMNI_SEARCH_FAIL = 'ALUMNI_SEARCH_FAIL'


