export const GENERATE_REPORT_REQUEST = 'GENERATE_REPORT_REQUEST'
export const GENERATE_REPORT_SUCCESS = 'GENERATE_REPORT_SUCCESS'
export const GENERATE_REPORT_FAIL = 'GENERATE_REPORT_FAIL'

export const LIST_REPORT_REQUEST = 'LIST_REPORT_REQUEST'
export const LIST_REPORT_SUCCESS = 'LIST_REPORT_SUCCESS'
export const LIST_REPORT_FAIL = 'LIST_REPORT_FAIL'